// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts,import_extension=none"
// @generated from file proto/cm/v1/cm.proto (package proto.cm.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetLsfJobsRequest, GetLsfJobsResponse, GetSettingsRequest, GetSettingsResponse, NewProjectRequest, NewProjectResponse, PingRequest, PingResponse, SetSettingsRequest, SetSettingsResponse } from "./cm_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service proto.cm.v1.CampaignManagerService
 */
export const CampaignManagerService = {
  typeName: "proto.cm.v1.CampaignManagerService",
  methods: {
    /**
     * @generated from rpc proto.cm.v1.CampaignManagerService.Ping
     */
    ping: {
      name: "Ping",
      I: PingRequest,
      O: PingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.cm.v1.CampaignManagerService.NewProject
     */
    newProject: {
      name: "NewProject",
      I: NewProjectRequest,
      O: NewProjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.cm.v1.CampaignManagerService.GetSettings
     */
    getSettings: {
      name: "GetSettings",
      I: GetSettingsRequest,
      O: GetSettingsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.cm.v1.CampaignManagerService.SetSettings
     */
    setSettings: {
      name: "SetSettings",
      I: SetSettingsRequest,
      O: SetSettingsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.cm.v1.CampaignManagerService.GetLsfJobs
     */
    getLsfJobs: {
      name: "GetLsfJobs",
      I: GetLsfJobsRequest,
      O: GetLsfJobsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

